name: Build Fritzing for Windows

on:
  workflow_dispatch:
    inputs:
      enable_ssh:
        description: 'Do you want to pause and open an SSH debug terminal?'
        required: true
        type: boolean
        default: false

jobs:
  build-windows:
    runs-on: windows-latest # Tells GitHub to use a fresh Windows machine

    steps:
    - name: Checkout Fritzing App
      uses: actions/checkout@v4
      with:
        path: fritzing-app

    - name: Checkout Fritzing Parts Library
      uses: actions/checkout@v4
      with:
        repository: fritzing/fritzing-parts
        path: fritzing-parts

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Provides a stable environment for aqtinstall

    - name: Remove WindowsApps from PATH
      shell: powershell
      run: |
        $oldPath = [Environment]::GetEnvironmentVariable("PATH", "Machine")
        $newPath = ($oldPath -split ';' | Where-Object { $_ -notlike "*WindowsApps*" }) -join ';'
        [Environment]::SetEnvironmentVariable("PATH", $newPath, "Machine")
        
        $env:PATH = ($env:PATH -split ';' | Where-Object { $_ -notlike "*WindowsApps*" }) -join ';'
        echo "PATH=$env:PATH" >> $env:GITHUB_ENV

    - name: Install Qt Framework
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.3'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'

    - name: Download and Fast Extract Boost
      shell: powershell
      run: |
        $ProgressPreference = 'SilentlyContinue'
        $url = "https://archives.boost.io/release/1.92.0/source/boost_1_92_0.zip"
        Invoke-WebRequest -Uri $url -OutFile "boost.zip"
        & "C:\Program Files\7-Zip\7z.exe" x boost.zip -y | Out-Null
        Rename-Item -Path "boost_1_92_0" -NewName "boost"
        Remove-Item "boost.zip"

    - name: Clone and Build Libgit2
      run: |
        git clone --branch v0.28.5 https://github.com/libgit2/libgit2.git
        cd libgit2
        mkdir build64
        cd build64
        cmake .. -G "MinGW Makefiles" \
          "-DCMAKE_POLICY_VERSION_MINIMUM=3.5" \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_SHARED_LIBS=ON \
          -DBUILD_CLAR=OFF
        cmake --build . --config Release

    - name: Setup Custom tmate Session
      if: ${{ inputs.enable_ssh == true }}
      uses: mxschmitt/action-tmate@v3
      with:
        # Change this to false to restore the browser web link
        limit-access-to-actor: false

    - name: Compile Fritzing App
      shell: cmd
      run: |
        cd fritzing-app
        qmake phoenix.pro "CONFIG+=release" "INCLUDEPATH+=../boost" "INCLUDEPATH+=../libgit2/include" "LIBS+=-L../libgit2/build64/Release -lgit2"
        nmake

    - name: Upload Finished Executable
      uses: actions/upload-artifact@v4
      with:
        name: Fritzing-Windows-Build
        path: fritzing-app/release/fritzing.exe # Collects your new free application
